### ISSUE TITLE
请问I和D是什么意思？

### ISSUE THREAD

**Issue by askerlee** [yhlhhhhh/Heterozygous-alleles-ratio-for-Wegene#1]
我把wegene数据传到别的网站，解析出错。查看数据发现很多II，还有少量DD。这些是什么意思呢？是不是把这些删掉就可以和别的网站兼容了？谢谢。

**Comment by yhlhhhhh** [comment]
I和D分别代表insertion和deletion，意思是碱基对的插入和缺失，至于传到其他网站失败的原因就不知道了。

**Comment by askerlee** [comment]
理解了，多谢。我在另一个网站看到了转换方法：
https://cloud.tencent.com/developer/article/1054773
